package dev.genesshoan.cinema_rest_api.dto.room;

/**
 * Response DTO representing a cinema room exposed by the API.
 *
 * <p>
 * Fields:
 * <ul>
 *   <li>{@code id} - unique identifier generated by the system</li>
 *   <li>{@code name} - human-readable room name</li>
 *   <li>{@code rows} - number of seat rows in the room</li>
 *   <li>{@code seatsPerRow} - number of seats per row</li>
 * </ul>
 * </p>
 */
public record RoomResponseDTO(
    Long id,
    String name,
    Integer rows,
    Integer seatsPerRow) {
}
