package dev.genesshoan.cinema_rest_api.dto;

import dev.genesshoan.cinema_rest_api.entity.SeatStatus;

/**
 * Response DTO representing a seat exposed by the API.
 *
 * <p>
 * Fields:
 * <ul>
 *   <li>{@code id} - unique identifier generated by the system</li>
 *   <li>{@code rowNumber} - the row number where the seat is located (1-indexed)</li>
 *   <li>{@code seatNumber} - the seat number within the row (1-indexed)</li>
 *   <li>{@code status} - the current availability status of the seat</li>
 *   <li>{@code showtimeId} - the ID of the showtime this seat belongs to</li>
 * </ul>
 * </p>
 */
public record SeatResponseDTO(
    Long id,
    Integer rowNumber,
    Integer seatNumber,
    SeatStatus status,
    Long showtimeId) {
}
