package dev.genesshoan.cinema_rest_api.mapper;

import org.springframework.stereotype.Component;

import dev.genesshoan.cinema_rest_api.dto.movie.MovieRequestDTO;
import dev.genesshoan.cinema_rest_api.dto.movie.MovieResponseDTO;
import dev.genesshoan.cinema_rest_api.entity.Movie;

/**
 * Mapper component for converting between Movie entities and DTOs.
 * 
 * This mapper handles the transformation between {@link Movie} entities
 * and their corresponding Data Transfer Objects ({@link MovieRequestDTO}
 * and {@link MovieResponseDTO}).
 * 
 * <p>
 * Mapping rules:
 * <ul>
 * <li>Entity to DTO: includes all fields including generated ID</li>
 * <li>DTO to Entity: excludes ID (generated by database)</li>
 * </ul>
 * </p>
 * 
 * @since 1.0.0
 */
@Component
public class MovieMapper {
  /**
   * Converts a Movie entity to a MovieResponseDTO.
   * 
   * Maps all fields from the entity to the response DTO, including
   * the generated ID.
   * 
   * @param movie the movie entity to convert, must not be null
   * @return the corresponding response DTO
   * @throws IllegalArgumentException if movie is null
   */
  public MovieResponseDTO toDto(Movie movie) {
    return new MovieResponseDTO(
        movie.getId(),
        movie.getTitle(),
        movie.getDurationMinutes(),
        movie.getGenre(),
        movie.getReleaseDate(),
        movie.getDescription());
  }

  /**
   * Converts a MovieRequestDTO to a Movie entity.
   * 
   * Creates a new Movie entity with all fields from the DTO.
   * The ID is not set and will be generated by the database.
   * 
   * @param movieRequestDTO the request DTO to convert, must not be null
   * @return a new Movie entity without ID
   * @throws IllegalArgumentException if movieRequestDTO is null
   */
  public Movie toEntity(MovieRequestDTO movieRequestDTO) {
    Movie movie = new Movie();
    movie.setTitle(movieRequestDTO.title());
    movie.setDurationMinutes(movieRequestDTO.durationMinutes());
    movie.setGenre(movieRequestDTO.genre());
    movie.setReleaseDate(movieRequestDTO.releaseDate());
    movie.setDescription(movieRequestDTO.description());

    return movie;
  }
}
